#!/usr/bin/expect
#Copyright (2016, ) Institute of Software, Chinese Academy of Sciences
# Author wuheng@otcaix.iscas.ac.cn
# Date 2016/11/1
# Version 2.0

set timeout 6
set hostname [lindex $argv 0]
set username [lindex $argv 1]
set password [lindex $argv 2]

#if [ "$username" -eq "root" ];then
spawn ssh-copy-id -i /root/.ssh/id_rsa.pub $username@$hostname
#else
#    spawn ssh-copy-id -i /home/$username/.ssh/id_rsa.pub $username@$hostname
#fi
expect {
	#first connect, no public key in ~/.ssh/known_hosts
	"Are you sure you want to continue connecting (yes/no)?" {
	send "yes\r"
	expect "password:"
		send "$password\r"：
	}
	#already has public key in ~/.ssh/known_hosts
	"password:" {
		send "$password\r"
	}
	"Now try logging into the machine" {
		#it has authorized, do nothing!
	}
}
expect eof
